[versions]
cloud = "2.1.0-SNAPSHOT"
cloudPaper = "2.0.0-SNAPSHOT"
paper = "1.21.3-R0.1-SNAPSHOT"
mccoroutine = "2.20.0"
koin = "4.0.0"
coroutine = "1.10.1"
serialization = "1.7.3"
reflect = "2.1.0"
ktor = "3.0.3"
junit = "5.11.3"
mockBukkit = "3.93.2"
commonsIo = "2.18.0"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
cloud = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloudPaper = { module = "org.incendo:cloud-paper", version.ref = "cloudPaper" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflect" }
mccoroutine-bukkit-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutine-bukkit-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-core", version.ref = "mccoroutine" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version = "2.3" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }
mock-bukkit = { group = "com.github.seeseemelk", name = "MockBukkit-v1.20", version.ref = "mockBukkit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit5 = { group = "io.insert-koin", name = "koin-test-junit5", version.ref = "koin" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }
resource-factory = { id = "xyz.jpenilla.resource-factory", version = "1.2.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.0" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.1.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }

[bundles]
commands = ["cloud", "cloudPaper", "cloud-annotations"]
coroutines = ["mccoroutine-bukkit-api", "mccoroutine-bukkit-core" , "kotlinx-coroutines-core"]
ktor-client = ["ktor-client-core", "ktor-client-cio", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]
koin-test = ["koin-test", "koin-test-junit5"]
