site_name: Minecraft Plugin Manager Docs
theme:
  name: material
  language: ja
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
  - i18n:
      docs_structure: folder
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
repo_url: https://github.com/Nlkomaru/MinecraftPluginManager
repo_name: Minecraft Plugin Manager
copyright: No Rights Reserved.
