api-version: '1.20'
name: MinecraftPluginManager
version: miencraft_plugin_version
main: dev.nikomaru.minecraftpluginmanager.MinecraftPluginManager
website: https://github.com/Nlkomaru/MinecraftPluginManager
libraries:
- com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.15.0
- com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.15.0
- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0
